name: Storm CMS Person
description: Storm CMS Person
config:
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.person:
          - basic
          - advanced
          - open_graph
          - twitter_cards
    workflows.workflow.editorial:
      addNodeTypes:
        - person
