name: Storm CMS Person
description: Storm CMS Person
recipes:
  - storm_cms_content_type_base
  - storm_cms_media
config:
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.person:
          - basic
          - advanced
          - open_graph
          - twitter_cards
    workflows.workflow.editorial:
      addNodeTypes:
        - person
